# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1c803845f74517d047af14f8cd3cf85402aa17ee459de4ace4e68d5ddafa5a6615317a8cac1b7b8c1afa67e4724f11f61a29f72b43ecd838d6eb22fb17530b

test:
  secret_key_base: 8e846d38211d84d44a2959dfa2dcdf3fbd8c82dc95cb9b3c42c1a56ae1a75470b43f4cc87df872cd954f4afda3afd3b47526a3d6c1438be172ca75c5375c2e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
